name: SMPCORE
version: '${projectVersion}'
main: com.smpcore.SMPCorePlugin
api-version: '1.20'
authors: [ "SMPCORE" ]
description: Paper plugin for SMP economy/trading/auction configuration.
commands:
  smpconfig:
    description: Manage SMPCORE configuration.
    usage: /smpconfig <reload|status|set>
    aliases: [smpc]
  balance:
    description: Show player balance.
    usage: /balance [player] [currency]
  pay:
    description: Pay a player.
    usage: /pay <player> <amount> [currency]
  eco:
    description: Admin economy controls.
    usage: /eco <set|add|remove> <player> <amount> [currency]
  trade:
    description: Trade with another player.
    usage: /trade <player|accept|pay>
  ah:
    description: Auction house command.
    usage: /ah <sell|browse|buy>
permissions:
  smpcore.admin:
    description: Access to all admin controls.
    default: op
  smpcore.sidebar.view:
    description: Receive the SMP status sidebar.
    default: true
