name: SMPCORE
version: '${projectVersion}'
main: com.smpcore.SMPCorePlugin
api-version: '1.20'
authors: [ "SMPCORE" ]
description: Configure SMP profile and core feature toggles.
commands:
  smpconfig:
    description: Manage SMPCORE configuration.
    usage: /smpconfig <reload|status>
    aliases: [smpc]
permissions:
  smpcore.admin:
    description: Access to all admin controls.
    default: op
  smpcore.sidebar.view:
    description: Receive the SMP status sidebar.
    default: true
